framework:
    cache:
        app: cache.adapter.apcu

        pools:
            # Used by Doctrine for query/result caching
            doctrine.result_cache_pool:
                adapter: cache.adapter.apcu
            doctrine.system_cache_pool:
                adapter: cache.adapter.apcu
