<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260301174720 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE common_name (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(5) NOT NULL, name VARCHAR(200) NOT NULL, species_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EEBB6697B2A1D860 ON common_name (species_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EEBB6697B2A1D8604180C698 ON common_name (species_id, locale)');
        $this->addSql('CREATE TABLE family (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, kingdom VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, url VARCHAR(500) NOT NULL, credit VARCHAR(300) DEFAULT NULL, species_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6A2CA10CB2A1D860 ON media (species_id)');
        $this->addSql('CREATE TABLE relationship (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, notes TEXT DEFAULT NULL, subject_id INT NOT NULL, object_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_200444A023EDC87 ON relationship (subject_id)');
        $this->addSql('CREATE INDEX IDX_200444A0232D562B ON relationship (object_id)');
        $this->addSql('CREATE TABLE species (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, scientific_name VARCHAR(150) NOT NULL, conservation_status VARCHAR(10) DEFAULT NULL, habitat VARCHAR(255) DEFAULT NULL, wingspan DOUBLE PRECISION DEFAULT NULL, max_height DOUBLE PRECISION DEFAULT NULL, substrate VARCHAR(100) DEFAULT NULL, family_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A50FF712C35E566A ON species (family_id)');
        $this->addSql('ALTER TABLE common_name ADD CONSTRAINT FK_EEBB6697B2A1D860 FOREIGN KEY (species_id) REFERENCES species (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10CB2A1D860 FOREIGN KEY (species_id) REFERENCES species (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE relationship ADD CONSTRAINT FK_200444A023EDC87 FOREIGN KEY (subject_id) REFERENCES species (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE relationship ADD CONSTRAINT FK_200444A0232D562B FOREIGN KEY (object_id) REFERENCES species (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE species ADD CONSTRAINT FK_A50FF712C35E566A FOREIGN KEY (family_id) REFERENCES family (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE common_name DROP CONSTRAINT FK_EEBB6697B2A1D860');
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10CB2A1D860');
        $this->addSql('ALTER TABLE relationship DROP CONSTRAINT FK_200444A023EDC87');
        $this->addSql('ALTER TABLE relationship DROP CONSTRAINT FK_200444A0232D562B');
        $this->addSql('ALTER TABLE species DROP CONSTRAINT FK_A50FF712C35E566A');
        $this->addSql('DROP TABLE common_name');
        $this->addSql('DROP TABLE family');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE relationship');
        $this->addSql('DROP TABLE species');
    }
}
