/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/common_names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of CommonName resources.
         * @description Retrieves the collection of CommonName resources.
         */
        get: operations["api_common_names_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common_names/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a CommonName resource.
         * @description Retrieves a CommonName resource.
         */
        get: operations["api_common_names_id_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/families": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Family resources.
         * @description Retrieves the collection of Family resources.
         */
        get: operations["api_families_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/families/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Family resource.
         * @description Retrieves a Family resource.
         */
        get: operations["api_families_id_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Media resources.
         * @description Retrieves the collection of Media resources.
         */
        get: operations["api_media_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Media resource.
         * @description Retrieves a Media resource.
         */
        get: operations["api_media_id_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Relationship resources.
         * @description Retrieves the collection of Relationship resources.
         */
        get: operations["api_relationships_get_collection"];
        put?: never;
        /**
         * Creates a Relationship resource.
         * @description Creates a Relationship resource.
         */
        post: operations["api_relationships_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationships/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Relationship resources.
         * @description Retrieves the collection of Relationship resources.
         */
        get: operations["api_relationshipsgraph_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationships/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Relationship resource.
         * @description Retrieves a Relationship resource.
         */
        get: operations["api_relationships_id_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Updates the Relationship resource.
         * @description Updates the Relationship resource.
         */
        patch: operations["api_relationships_id_patch"];
        trace?: never;
    };
    "/api/relationships/{relationshipId}/translations/{locale}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Updates the RelationshipTranslation resource.
         * @description Updates the RelationshipTranslation resource.
         */
        patch: operations["api_relationships_relationshipIdtranslations_locale_patch"];
        trace?: never;
    };
    "/api/species": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Species resources.
         * @description Retrieves the collection of Species resources.
         */
        get: operations["api_species_get_collection"];
        put?: never;
        /**
         * Creates a Species resource.
         * @description Creates a Species resource.
         */
        post: operations["api_species_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/species/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Species resource.
         * @description Retrieves a Species resource.
         */
        get: operations["api_species_id_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Updates the Species resource.
         * @description Updates the Species resource.
         */
        patch: operations["api_species_id_patch"];
        trace?: never;
    };
    "/api/species/{speciesId}/translations/{locale}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Updates the SpeciesTranslation resource.
         * @description Updates the SpeciesTranslation resource.
         */
        patch: operations["api_species_speciesIdtranslations_locale_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CommonName: {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            species?: string;
            /**
             * @default
             * @enum {string}
             */
            locale: "en" | "fr" | "la";
            /** @default  */
            name: string;
        };
        "CommonName-relationship.read": {
            /**
             * @default
             * @enum {string}
             */
            locale: "en" | "fr" | "la";
            /** @default  */
            name: string;
        };
        "CommonName-species.read": {
            /**
             * @default
             * @enum {string}
             */
            locale: "en" | "fr" | "la";
            /** @default  */
            name: string;
        };
        "CommonName-species.write": {
            /**
             * @default
             * @enum {string}
             */
            locale: "en" | "fr" | "la";
            /** @default  */
            name: string;
        };
        "CommonName.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            species?: string;
            /**
             * @default
             * @enum {string}
             */
            locale: "en" | "fr" | "la";
            /** @default  */
            name: string;
        };
        "CommonName.jsonld-relationship.read": components["schemas"]["HydraItemBaseSchema"] & {
            /**
             * @default
             * @enum {string}
             */
            locale: "en" | "fr" | "la";
            /** @default  */
            name: string;
        };
        "CommonName.jsonld-species.read": components["schemas"]["HydraItemBaseSchema"] & {
            /**
             * @default
             * @enum {string}
             */
            locale: "en" | "fr" | "la";
            /** @default  */
            name: string;
        };
        /** @description Unprocessable entity */
        ConstraintViolation: {
            /** @default 422 */
            status: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath: string;
                /** @description The message associated with the violation */
                message: string;
                /** @description The code of the violation */
                code?: string;
                /** @description An extra hint to understand the violation */
                hint?: string;
                /** @description The serialized payload of the violation */
                payload?: {
                    [key: string]: unknown;
                };
            }[];
            readonly detail?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        /** @description Unprocessable entity */
        "ConstraintViolation.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @default 422 */
            status: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath: string;
                /** @description The message associated with the violation */
                message: string;
                /** @description The code of the violation */
                code?: string;
                /** @description An extra hint to understand the violation */
                hint?: string;
                /** @description The serialized payload of the violation */
                payload?: {
                    [key: string]: unknown;
                };
            }[];
            readonly detail?: string;
            readonly description?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        /** @description A representation of common errors. */
        Error: {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
        };
        /** @description A representation of common errors. */
        "Error.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
            readonly description?: string | null;
        };
        Family: {
            id: number;
            /** @default  */
            name: string;
            /**
             * @default
             * @enum {string}
             */
            kingdom: "bird" | "tree" | "fungus";
            readonly species?: string[];
        };
        "Family-relationship.read": {
            id: number;
            /** @default  */
            name: string;
            /**
             * @default
             * @enum {string}
             */
            kingdom: "bird" | "tree" | "fungus";
        };
        "Family-species.read": {
            id: number;
            /** @default  */
            name: string;
            /**
             * @default
             * @enum {string}
             */
            kingdom: "bird" | "tree" | "fungus";
        };
        "Family.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            id: number;
            /** @default  */
            name: string;
            /**
             * @default
             * @enum {string}
             */
            kingdom: "bird" | "tree" | "fungus";
            readonly species?: string[];
        };
        "Family.jsonld-relationship.read": components["schemas"]["HydraItemBaseSchema"] & {
            id: number;
            /** @default  */
            name: string;
            /**
             * @default
             * @enum {string}
             */
            kingdom: "bird" | "tree" | "fungus";
        };
        "Family.jsonld-species.read": components["schemas"]["HydraItemBaseSchema"] & {
            id: number;
            /** @default  */
            name: string;
            /**
             * @default
             * @enum {string}
             */
            kingdom: "bird" | "tree" | "fungus";
        };
        HydraCollectionBaseSchema: components["schemas"]["HydraCollectionBaseSchemaNoPagination"] & {
            /**
             * @example {
             *       "@id": "string",
             *       "@type": "string",
             *       "first": "string",
             *       "last": "string",
             *       "previous": "string",
             *       "next": "string"
             *     }
             */
            view?: {
                /** Format: iri-reference */
                "@id"?: string;
                "@type"?: string;
                /** Format: iri-reference */
                first?: string;
                /** Format: iri-reference */
                last?: string;
                /** Format: iri-reference */
                previous?: string;
                /** Format: iri-reference */
                next?: string;
            };
        };
        HydraCollectionBaseSchemaNoPagination: {
            totalItems?: number;
            search?: {
                "@type"?: string;
                template?: string;
                variableRepresentation?: string;
                mapping?: {
                    "@type"?: string;
                    variable?: string;
                    property?: string | null;
                    required?: boolean;
                }[];
            };
        };
        HydraItemBaseSchema: {
            "@context"?: string | ({
                "@vocab": string;
                /** @enum {string} */
                hydra: "http://www.w3.org/ns/hydra/core#";
            } & {
                [key: string]: unknown;
            });
            "@id": string;
            "@type": string;
        };
        Media: {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            species?: string;
            /**
             * @default
             * @enum {string}
             */
            type: "image" | "audio" | "leaf" | "feather";
            /** @default  */
            url: string;
            credit?: string | null;
        };
        "Media-species.read": {
            /**
             * @default
             * @enum {string}
             */
            type: "image" | "audio" | "leaf" | "feather";
            /** @default  */
            url: string;
            credit?: string | null;
        };
        "Media.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            species?: string;
            /**
             * @default
             * @enum {string}
             */
            type: "image" | "audio" | "leaf" | "feather";
            /** @default  */
            url: string;
            credit?: string | null;
        };
        "Media.jsonld-species.read": components["schemas"]["HydraItemBaseSchema"] & {
            /**
             * @default
             * @enum {string}
             */
            type: "image" | "audio" | "leaf" | "feather";
            /** @default  */
            url: string;
            credit?: string | null;
        };
        "Relationship-relationship.graph": {
            subject: components["schemas"]["Species-relationship.graph"];
            object: components["schemas"]["Species-relationship.graph"];
            /**
             * @default
             * @enum {string}
             */
            type: "nests_in" | "grows_on" | "feeds_on" | "symbiosis_with" | "disperses_seeds_of" | "disperses_spores_of" | "mycorrhiza_with" | "parasitises";
        };
        "Relationship-relationship.read": {
            id: number;
            subject: components["schemas"]["Species-relationship.read"];
            object: components["schemas"]["Species-relationship.read"];
            /**
             * @default
             * @enum {string}
             */
            type: "nests_in" | "grows_on" | "feeds_on" | "symbiosis_with" | "disperses_seeds_of" | "disperses_spores_of" | "mycorrhiza_with" | "parasitises";
            notes?: string | null;
            translations: components["schemas"]["RelationshipTranslation-relationship.read"][];
        };
        "Relationship-relationship.write": {
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            subject: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            object: string;
            /**
             * @default
             * @enum {string}
             */
            type: "nests_in" | "grows_on" | "feeds_on" | "symbiosis_with" | "disperses_seeds_of" | "disperses_spores_of" | "mycorrhiza_with" | "parasitises";
            notes?: string | null;
            translations: components["schemas"]["RelationshipTranslation-relationship.write.jsonMergePatch"][];
        };
        "Relationship-relationship.write.jsonMergePatch": {
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            subject?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            object?: string;
            /**
             * @default
             * @enum {string}
             */
            type: "nests_in" | "grows_on" | "feeds_on" | "symbiosis_with" | "disperses_seeds_of" | "disperses_spores_of" | "mycorrhiza_with" | "parasitises";
            notes?: string | null;
            translations?: components["schemas"]["RelationshipTranslation-relationship.write.jsonMergePatch"][];
        };
        "Relationship.jsonld-relationship.graph": components["schemas"]["HydraItemBaseSchema"] & {
            subject: components["schemas"]["Species.jsonld-relationship.graph"];
            object: components["schemas"]["Species.jsonld-relationship.graph"];
            /**
             * @default
             * @enum {string}
             */
            type: "nests_in" | "grows_on" | "feeds_on" | "symbiosis_with" | "disperses_seeds_of" | "disperses_spores_of" | "mycorrhiza_with" | "parasitises";
        };
        "Relationship.jsonld-relationship.read": components["schemas"]["HydraItemBaseSchema"] & {
            id: number;
            subject: components["schemas"]["Species.jsonld-relationship.read"];
            object: components["schemas"]["Species.jsonld-relationship.read"];
            /**
             * @default
             * @enum {string}
             */
            type: "nests_in" | "grows_on" | "feeds_on" | "symbiosis_with" | "disperses_seeds_of" | "disperses_spores_of" | "mycorrhiza_with" | "parasitises";
            notes?: string | null;
            translations: components["schemas"]["RelationshipTranslation.jsonld-relationship.read"][];
        };
        "RelationshipTranslation-relationship.read": {
            /**
             * @default
             * @enum {string}
             */
            locale: "en" | "fr";
            notes?: string | null;
        };
        "RelationshipTranslation-relationship.write.jsonMergePatch": {
            /**
             * @default
             * @enum {string}
             */
            locale: "en" | "fr";
            notes?: string | null;
        };
        "RelationshipTranslation-translation.write.jsonMergePatch": {
            notes?: string | null;
        };
        "RelationshipTranslation.jsonld-relationship.read": components["schemas"]["HydraItemBaseSchema"] & {
            /**
             * @default
             * @enum {string}
             */
            locale: "en" | "fr";
            notes?: string | null;
        };
        "Species-relationship.graph": {
            id: number;
        };
        "Species-relationship.read": {
            id: number;
            /** @default  */
            scientificName: string;
            family: components["schemas"]["Family-relationship.read"];
            slug?: string | null;
            commonNames: components["schemas"]["CommonName-relationship.read"][];
        };
        "Species-species.read": {
            id: number;
            /** @default  */
            scientificName: string;
            family: components["schemas"]["Family-species.read"];
            /** @enum {string|null} */
            conservationStatus?: "EX" | "EW" | "CR" | "EN" | "VU" | "NT" | "LC" | "DD" | "NE" | null;
            habitat?: string | null;
            wingspan?: number | null;
            maxHeight?: number | null;
            slug?: string | null;
            substrate?: string | null;
            /** @default 0 */
            relationshipCount: number;
            commonNames: components["schemas"]["CommonName-species.read"][];
            translations: components["schemas"]["SpeciesTranslation-species.read"][];
            readonly media: components["schemas"]["Media-species.read"][];
        };
        "Species-species.write": {
            /** @default  */
            scientificName: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            family: string;
            /** @enum {string|null} */
            conservationStatus?: "EX" | "EW" | "CR" | "EN" | "VU" | "NT" | "LC" | "DD" | "NE" | null;
            habitat?: string | null;
            wingspan?: number | null;
            maxHeight?: number | null;
            substrate?: string | null;
            commonNames: components["schemas"]["CommonName-species.write"][];
            translations: components["schemas"]["SpeciesTranslation-species.write.jsonMergePatch"][];
        };
        "Species-species.write.jsonMergePatch": {
            /** @default  */
            scientificName: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            family?: string;
            /** @enum {string|null} */
            conservationStatus?: "EX" | "EW" | "CR" | "EN" | "VU" | "NT" | "LC" | "DD" | "NE" | null;
            habitat?: string | null;
            wingspan?: number | null;
            maxHeight?: number | null;
            substrate?: string | null;
            commonNames?: components["schemas"]["CommonName-species.write"][];
            translations?: components["schemas"]["SpeciesTranslation-species.write.jsonMergePatch"][];
        };
        "Species.jsonld-relationship.graph": components["schemas"]["HydraItemBaseSchema"] & {
            id: number;
        };
        "Species.jsonld-relationship.read": components["schemas"]["HydraItemBaseSchema"] & {
            id: number;
            /** @default  */
            scientificName: string;
            family: components["schemas"]["Family.jsonld-relationship.read"];
            slug?: string | null;
            commonNames: components["schemas"]["CommonName.jsonld-relationship.read"][];
        };
        "Species.jsonld-species.read": components["schemas"]["HydraItemBaseSchema"] & {
            id: number;
            /** @default  */
            scientificName: string;
            family: components["schemas"]["Family.jsonld-species.read"];
            /** @enum {string|null} */
            conservationStatus?: "EX" | "EW" | "CR" | "EN" | "VU" | "NT" | "LC" | "DD" | "NE" | null;
            habitat?: string | null;
            wingspan?: number | null;
            maxHeight?: number | null;
            slug?: string | null;
            substrate?: string | null;
            /** @default 0 */
            relationshipCount: number;
            commonNames: components["schemas"]["CommonName.jsonld-species.read"][];
            translations: components["schemas"]["SpeciesTranslation.jsonld-species.read"][];
            readonly media: components["schemas"]["Media.jsonld-species.read"][];
        };
        "SpeciesTranslation-species.read": {
            /**
             * @default
             * @enum {string}
             */
            locale: "en" | "fr";
            habitat?: string | null;
            substrate?: string | null;
        };
        "SpeciesTranslation-species.write.jsonMergePatch": {
            /**
             * @default
             * @enum {string}
             */
            locale: "en" | "fr";
            habitat?: string | null;
            substrate?: string | null;
        };
        "SpeciesTranslation-translation.write.jsonMergePatch": {
            habitat?: string | null;
            substrate?: string | null;
        };
        "SpeciesTranslation.jsonld-species.read": components["schemas"]["HydraItemBaseSchema"] & {
            /**
             * @default
             * @enum {string}
             */
            locale: "en" | "fr";
            habitat?: string | null;
            substrate?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_common_names_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CommonName collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["CommonName.jsonld"][];
                    };
                    "application/json": components["schemas"]["CommonName"][];
                };
            };
        };
    };
    api_common_names_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CommonName identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CommonName resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["CommonName.jsonld"];
                    "application/json": components["schemas"]["CommonName"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_families_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Family collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Family.jsonld"][];
                    };
                    "application/json": components["schemas"]["Family"][];
                };
            };
        };
    };
    api_families_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Family identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Family resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Family.jsonld"];
                    "application/json": components["schemas"]["Family"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_media_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Media.jsonld"][];
                    };
                    "application/json": components["schemas"]["Media"][];
                };
            };
        };
    };
    api_media_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Media identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Media.jsonld"];
                    "application/json": components["schemas"]["Media"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_relationships_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                /** @description Enable or disable pagination */
                pagination?: boolean;
                type?: string;
                "type[]"?: string[];
                subject?: string;
                "subject[]"?: string[];
                object?: string;
                "object[]"?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relationship collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Relationship.jsonld-relationship.read"][];
                    };
                    "application/json": components["schemas"]["Relationship-relationship.read"][];
                };
            };
        };
    };
    api_relationships_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Relationship resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Relationship-relationship.write"];
                "application/json": components["schemas"]["Relationship-relationship.write"];
            };
        };
        responses: {
            /** @description Relationship resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Relationship.jsonld-relationship.read"];
                    "application/json": components["schemas"]["Relationship-relationship.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_relationshipsgraph_get_collection: {
        parameters: {
            query?: {
                /** @description Enable or disable pagination */
                pagination?: boolean;
                type?: string;
                "type[]"?: string[];
                subject?: string;
                "subject[]"?: string[];
                object?: string;
                "object[]"?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relationship collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchemaNoPagination"] & {
                        member: components["schemas"]["Relationship.jsonld-relationship.graph"][];
                    };
                    "application/json": components["schemas"]["Relationship-relationship.graph"][];
                };
            };
        };
    };
    api_relationships_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relationship identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relationship resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Relationship.jsonld-relationship.read"];
                    "application/json": components["schemas"]["Relationship-relationship.read"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_relationships_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relationship identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Relationship resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["Relationship-relationship.write.jsonMergePatch"];
            };
        };
        responses: {
            /** @description Relationship resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Relationship.jsonld-relationship.read"];
                    "application/json": components["schemas"]["Relationship-relationship.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_relationships_relationshipIdtranslations_locale_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relationship identifier */
                relationshipId: string;
                /** @description RelationshipTranslation identifier */
                locale: string;
            };
            cookie?: never;
        };
        /** @description The updated RelationshipTranslation resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["RelationshipTranslation-translation.write.jsonMergePatch"];
            };
        };
        responses: {
            /** @description RelationshipTranslation resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["RelationshipTranslation.jsonld-relationship.read"];
                    "application/json": components["schemas"]["RelationshipTranslation-relationship.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_species_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                /** @description Enable or disable pagination */
                pagination?: boolean;
                id?: number;
                "id[]"?: number[];
                "family.name"?: string;
                "family.kingdom"?: string;
                "family.kingdom[]"?: string[];
                slug?: string;
                "slug[]"?: string[];
                scientificName?: string;
                "commonNames.name"?: string;
                "order[scientificName]"?: "asc" | "desc";
                "order[relationshipCount]"?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Species collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Species.jsonld-species.read"][];
                    };
                    "application/json": components["schemas"]["Species-species.read"][];
                };
            };
        };
    };
    api_species_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Species resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Species-species.write"];
                "application/json": components["schemas"]["Species-species.write"];
            };
        };
        responses: {
            /** @description Species resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Species.jsonld-species.read"];
                    "application/json": components["schemas"]["Species-species.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_species_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Species identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Species resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Species.jsonld-species.read"];
                    "application/json": components["schemas"]["Species-species.read"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_species_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Species identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Species resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["Species-species.write.jsonMergePatch"];
            };
        };
        responses: {
            /** @description Species resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Species.jsonld-species.read"];
                    "application/json": components["schemas"]["Species-species.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_species_speciesIdtranslations_locale_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Species identifier */
                speciesId: string;
                /** @description SpeciesTranslation identifier */
                locale: string;
            };
            cookie?: never;
        };
        /** @description The updated SpeciesTranslation resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["SpeciesTranslation-translation.write.jsonMergePatch"];
            };
        };
        responses: {
            /** @description SpeciesTranslation resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["SpeciesTranslation.jsonld-species.read"];
                    "application/json": components["schemas"]["SpeciesTranslation-species.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
}
